---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/cars":
    get:
      summary: list cars
      tags:
      - Cars
      responses:
        '200':
          description: successful
    post:
      summary: create car
      tags:
      - Cars
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                make:
                  type: string
                  example: Audi
                model:
                  type: string
                  example: Mustang
                year:
                  type: integer
                  example: 2021
                color:
                  type: string
                  example: Yellow
                body_type:
                  type: string
                  example: Sedan
                engine_capacity:
                  type: integer
                  example: 1 Cylinder Engine
                engine_cylinders:
                  type: integer
                  example: 3 Cylinder Engine
                turbo:
                  type: boolean
                  example: false
                horsepower:
                  type: integer
                  example: 601
                torque:
                  type: integer
                  example: 270
                weight:
                  type: integer
                  example: 1624
                drivetrain:
                  type: string
                  example: RWD
                transmission:
                  type: string
                  example: Automatic
                fuel_type:
                  type: string
                  example: E-85/Gasoline
                doors:
                  type: integer
                  example: 4
                seats:
                  type: integer
                  example: 4
                mileage:
                  type: integer
                  example: 36466
                price:
                  type: integer
                  example: 2272.22
                description:
                  type: string
                  example: Omnis accusantium quis. Accusantium nobis aperiam. Ut provident
                    ea.
                image:
                  type: string
                  example: http://bode.example/donald
              required:
              - make
              - model
              - year
              - color
              - body_type
              - engine_capacity
              - engine_cylinders
              - turbo
              - horsepower
              - torque
              - weight
              - drivetrain
              - transmission
              - fuel_type
              - doors
              - seats
              - mileage
              - price
              - description
              - image
  "/api/v1/cars/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show car
      tags:
      - Cars
      responses:
        '200':
          description: successful
    delete:
      summary: delete car
      tags:
      - Cars
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000/
