---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/cars":
    get:
      summary: list cars
      tags:
      - Cars
      responses:
        '200':
          description: successful
    post:
      summary: create car
      tags:
      - Cars
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                make:
                  type: string
                  example: Nissan
                model:
                  type: string
                  example: MKZ
                year:
                  type: integer
                  example: 2021
                color:
                  type: string
                  example: Violet
                body_type:
                  type: string
                  example: Passenger Van
                engine_capacity:
                  type: integer
                  example: 2 Cylinder Engine
                engine_cylinders:
                  type: integer
                  example: 2 Cylinder Engine
                turbo:
                  type: boolean
                  example: false
                horsepower:
                  type: integer
                  example: 494
                torque:
                  type: integer
                  example: 490
                weight:
                  type: integer
                  example: 4359
                drivetrain:
                  type: string
                  example: FWD
                transmission:
                  type: string
                  example: CVT
                fuel_type:
                  type: string
                  example: Diesel
                doors:
                  type: integer
                  example: 2
                seats:
                  type: integer
                  example: 5
                mileage:
                  type: integer
                  example: 27762
                price:
                  type: integer
                  example: 6433.05
                description:
                  type: string
                  example: Numquam voluptatem quod. Eveniet deleniti molestiae. Doloremque
                    nostrum recusandae.
                image:
                  type: string
                  example: http://turcotte-jenkins.test/nancie_buckridge
              required:
              - make
              - model
              - year
              - color
              - body_type
              - engine_capacity
              - engine_cylinders
              - turbo
              - horsepower
              - torque
              - weight
              - drivetrain
              - transmission
              - fuel_type
              - doors
              - seats
              - mileage
              - price
              - description
              - image
  "/api/v1/cars/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show car
      tags:
      - Cars
      responses:
        '200':
          description: successful
    delete:
      summary: delete car
      tags:
      - Cars
      responses:
        '200':
          description: successful
  "/api/v1/users":
    get:
      summary: list users
      tags:
      - Users
      responses:
        '200':
          description: successful
    post:
      summary: create user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: nestor.oreilly
              required:
              - username
  "/api/v1/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      tags:
      - Users
      responses:
        '200':
          description: successful
    patch:
      summary: update user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: colby
              required:
              - username
    delete:
      summary: delete user
      tags:
      - Users
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000/
