# rubocop:disable all
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
User.destroy_all

users = User.create([
                      { username: 'johndoe' },
                      { username: 'janedoe' },
                      { username: 'johndoe2' },
                      { username: 'janedoe2' }
                    ])

# car attributes
# make, model, year, color, body_type, engine_capacity, engine_cylinders, turbo, horsepower, torque, weight, drivetrain, transmission, fuel_type, doors, seats, mileage, price, description, image
Car.destroy_all

cars = Car.create([
                    {
                      make: 'Honda',
                      model: 'Civic Type R',
                      year: 2017,
                      color: 'Championship White',
                      body_type: 'Hatchback',
                      engine_capacity: 2.0,
                      engine_cylinders: 4,
                      turbo: true,
                      horsepower: 306,
                      torque: 295,
                      weight: 3117,
                      drivetrain: 'Front-Wheel Drive',
                      transmission: '6-Speed Manual',
                      fuel_type: 'Gasoline',
                      doors: 4,
                      seats: 4,
                      mileage: 0,
                      price: 34_800,
                      description: 'The 2017 Honda Civic Type R is a high-performance hatchback that delivers thrilling driving dynamics, sharp handling, and impressive acceleration.',
                      image: 'https://res.cloudinary.com/djqt4g3pl/image/upload/v1684148093/samples/cars/2017_honda_civic_type_r_5-HD_ecitlh.jpg'
                    },
                    {
                      make: 'Tesla',
                      model: 'Model S',
                      year: 2022,
                      color: 'Deep Blue Metallic',
                      body_type: 'Sedan',
                      engine_capacity: nil,
                      engine_cylinders: nil,
                      turbo: false,
                      horsepower: 670,
                      torque: 750,
                      weight: 4941,
                      drivetrain: 'Dual Motor All-Wheel Drive',
                      transmission: 'Single Speed Fixed Gear',
                      fuel_type: 'Electric',
                      doors: 4,
                      seats: 5,
                      mileage: 0,
                      price: 79_990,
                      description: 'The Tesla Model S is a high-performance electric sedan that offers blistering acceleration, advanced technology, and long-range driving capabilities.',
                      image: 'https://res.cloudinary.com/djqt4g3pl/image/upload/v1684148122/samples/cars/2022_tesla_model_s_plaid_5k-HD_ul33zu.jpg'
                    },
                    {
                      make: 'Dodge',
                      model: 'Challenger',
                      year: 2021,
                      color: 'Octane Red Pearlcoat',
                      body_type: 'Coupe',
                      engine_capacity: 6.2,
                      engine_cylinders: 8,
                      turbo: true,
                      horsepower: 717,
                      torque: 656,
                      weight: 4480,
                      drivetrain: 'Rear-Wheel Drive',
                      transmission: '6-Speed Manual',
                      fuel_type: 'Gasoline',
                      doors: 2,
                      seats: 5,
                      mileage: 0,
                      price: 70_895,
                      description: 'The Dodge Challenger Hellcat is a high-performance muscle car that offers a supercharged V8 engine, aggressive styling, and an iconic heritage.',
                      image: '2021-dodge-challenger-srt-hellcat.jpg'
                    },
                    {
                      make: 'Porsche',
                      model: '911',
                      year: 2022,
                      color: 'GT Silver Metallic',
                      body_type: 'Coupe',
                      engine_capacity: '3.0L',
                      engine_cylinders: 6,
                      turbo: true,
                      horsepower: 443,
                      torque: 390,
                      weight: 3296,
                      drivetrain: 'Rear-Wheel Drive',
                      transmission: '8-Speed Porsche Doppelkupplung (PDK)',
                      fuel_type: 'Gasoline',
                      doors: 2,
                      seats: 4,
                      mileage: 0,
                      price: 99_999,
                      description: 'The 2022 Porsche 911 delivers a comfortable and luxurious ride, with exceptional handling and acceleration. The iconic design is complemented by state-of-the-art technology and premium materials throughout the cabin.',
                      image: '2022_porsche_911_gt3_touring_49.jpg'
                    },
                    {
                      make: 'BMW',
                      model: 'i8',
                      year: '2019',
                      color: 'E-Copper Metallic',
                      body_type: 'Coupe',
                      engine_capacity: '1.5L',
                      engine_cylinders: 3,
                      turbo: true,
                      horsepower: 369,
                      torque: 420,
                      weight: 3373,
                      drivetrain: 'AWD',
                      transmission: '6-speed automatic',
                      fuel_type: 'Hybrid',
                      doors: 2,
                      seats: 4,
                      mileage: 10_000,
                      price: 95_000,
                      description: "The BMW i8 is a plug-in hybrid sports car that is designed to thrill. With its striking, futuristic design and impressive performance capabilities, it's no wonder that the i8 has become one of the most sought-after cars on the market.",
                      image: '2019-bmw-i8-roadster.jpg'
                    },
                    {
                      make: 'Ford',
                      model: 'Mustang Shelby',
                      year: '2021',
                      color: 'Carbonized Gray',
                      body_type: 'Coupe',
                      engine_capacity: '5.2L',
                      engine_cylinders: 8,
                      turbo: true,
                      horsepower: 760,
                      torque: 625,
                      weight: 4023,
                      drivetrain: 'RWD',
                      transmission: '6-speed manual',
                      fuel_type: 'Gasoline',
                      doors: 2,
                      seats: 4,
                      mileage: 0,
                      price: 78_000,
                      description: 'The 2021 Ford Mustang Shelby GT500 is a high-performance variant of the Mustang designed and manufactured by Ford Performance. It features a supercharged 5.2-liter V8 engine that produces 760 horsepower and 625 lb-ft of torque. It has a top speed of 180 mph and can go from 0 to 60 mph in just 3.3 seconds.',
                      image: '2021-Ford-Mustang-Shelby-GT500-3.jpg'
                    },
                    {
                      make: 'Chevrolet',
                      model: 'Corvette Stingray',
                      year: 2020,
                      color: 'Arctic White',
                      body_type: 'Coupe',
                      engine_capacity: 6.2,
                      engine_cylinders: 8,
                      turbo: false,
                      horsepower: 495,
                      torque: 470,
                      weight: 3366,
                      drivetrain: 'Rear-Wheel Drive',
                      transmission: '8-Speed Dual-Clutch Automatic',
                      fuel_type: 'Gasoline',
                      doors: 2,
                      seats: 2,
                      mileage: 0,
                      price: 58_995,
                      description: 'The 2020 Chevrolet Corvette Stingray is a mid-engine sports car that combines power and precision for an exhilarating driving experience. With its sleek design and advanced technology, this car is sure to turn heads on the road.',
                      image: 'chevrolet-corvette-c8-stingray-2020.jpg'
                    },
                    {
                      make: 'Toyota',
                      model: 'GR Yaris',
                      year: 2021,
                      color: 'White',
                      body_type: 'Hatchback',
                      engine_capacity: 1.6,
                      engine_cylinders: 3,
                      turbo: true,
                      horsepower: 257,
                      torque: 266,
                      weight: 2800,
                      drivetrain: 'All-Wheel Drive',
                      transmission: '6-Speed Manual',
                      fuel_type: 'Gasoline',
                      doors: 3,
                      seats: 4,
                      mileage: 0,
                      price: 32_000,
                      description: "The 2021 Toyota GR Yaris is a rally-inspired hot hatchback that boasts impressive performance capabilities and a sleek, sporty design. With its powerful 1.6-liter turbocharged engine and all-wheel drive system, this car is a true driver's delight.",
                      image: 'Toyota-GR-Yaris-Japan-24.jpg'
                    },
                    {
                      make: 'Audi',
                      model: 'RS6 Avant',
                      year: 2021,
                      color: 'Mythos Black Metallic',
                      body_type: 'Wagon',
                      engine_capacity: 4.0,
                      engine_cylinders: 8,
                      turbo: true,
                      horsepower: 591,
                      torque: 590,
                      weight: 4510,
                      drivetrain: 'All-Wheel Drive',
                      transmission: '8-Speed Automatic',
                      fuel_type: 'Gasoline',
                      doors: 5,
                      seats: 5,
                      mileage: 0,
                      price: 109_995,
                      description: 'The Audi RS6 Avant is a performance wagon that delivers an exhilarating driving experience with its powerful engine, advanced technology, and luxurious features.',
                      image: 'audi_rs_6_avant_performance_5k-HD.jpg'
                    },
                    {
                      make: 'Mercedes-Benz',
                      model: 'AMG GT',
                      year: '2021',
                      color: 'Selenite Grey Metallic',
                      body_type: 'Coupe',
                      engine_capacity: '4.0',
                      engine_cylinders: 8,
                      turbo: true,
                      horsepower: 523,
                      torque: 494,
                      weight: 3770,
                      drivetrain: 'RWD',
                      transmission: '7-speed automatic',
                      fuel_type: 'Gasoline',
                      doors: 2,
                      seats: 2,
                      mileage: 0,
                      price: 140_000,
                      description: "The Mercedes-AMG GT is a two-door sports car that offers a thrilling driving experience. The car's V8 engine produces an impressive amount of power and torque, and it can accelerate from 0 to 60 mph in just over 3 seconds. The AMG GT also features a luxurious and well-appointed interior, with high-quality materials and advanced technology.",
                      image: 'mercedes_amg_gt_night_edition_2021_4k_2-HD.jpg'
                    }
                  ])

# Reservation attributes
# user_id, car_id, reservation_date, city
Reservation.destroy_all

reservations = Reservation.create([
                                    { user_id: 1, car_id: 1, reservation_date: '2023-05-08', city: 'Nairobi' },
                                    { user_id: 2, car_id: 2, reservation_date: '2023-05-08', city: 'Lagos' },
                                    { user_id: 3, car_id: 3, reservation_date: '2023-05-10', city: 'Baghdad' },
                                    { user_id: 4, car_id: 4, reservation_date: '2023-05-10', city: 'Cairo' },
                                    { user_id: 1, car_id: 5, reservation_date: '2023-05-12', city: 'Nairobi' },
                                    { user_id: 2, car_id: 6, reservation_date: '2023-05-12', city: 'Johannesburg' },
                                    { user_id: 3, car_id: 7, reservation_date: '2023-05-14', city: 'Lagos' },
                                    { user_id: 4, car_id: 8, reservation_date: '2023-05-14', city: 'Nairobi' },
                                    { user_id: 1, car_id: 9, reservation_date: '2023-05-16', city: 'Cairo' },
                                    { user_id: 2, car_id: 10, reservation_date: '2023-05-16', city: 'Baghdad' }
                                  ])
